config/routes.rb
Rails.application.routes.draw do
  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :leads
  resources :migrations
  resources :employees
  resources :quotes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  # get 'leads/new'
  
  root 'welcome#index'

  post 'lead' => 'leads#create'

  # post 'lead' => 'leads#sendgrid'
  

  get 'residential' => 'welcome#residential'

  get 'commercial' => 'welcome#commercial'

  # get '/admin' => 'rails_admin#admin'
  
  get 'quote' => 'welcome#quote'
  post 'quote' => 'quotes#create'

  get 'quote' => 'quotes#new'

  get 'map' => 'googlemaps#map'

  get '/intervention' => 'interventions#new'

  get 'get_buildings_by_customer/:customer_id', to: 'buildings#get_buildings_by_customer'  
  get '/building_search' => 'buildings#building_search'

  get 'get_batteries_by_buildings/:building_id', to: 'batteries#get_batteries_by_buildings'  
  get '/battery_search' => 'batteries#battery_search'

  get 'get_columns_by_batteries/:battery_id', to: 'columns#get_columns_by_batteries'  
  get '/column_search' => 'columns#column_search'

  get 'get_elevators_by_columns/:column_id', to: 'elevators#get_elevators_by_columns'  
  get '/elevator_search' => 'elevators#elevator_search'

end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :user
    has_many :batteries
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:First_Name, :Last_Name, :Title_Or_Function, :Email)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :First_Name %>
    <%= form.text_field :First_Name %>
  </div>

  <div class="field">
    <%= form.label :Last_Name %>
    <%= form.text_field :Last_Name %>
  </div>

  <div class="field">
    <%= form.label :Title_Or_Function %>
    <%= form.text_field :Title_Or_Function %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :Email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Title or function</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.First_Name %></td>
        <td><%= employee.Last_Name %></td>
        <td><%= employee.Title_Or_Function %></td>
        <td><%= employee.Email %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee.First_Name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.Last_Name %>
</p>

<p>
  <strong>Title or function:</strong>
  <%= @employee.Title_Or_Function %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.Email %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>