config/routes.rb
Rails.application.routes.draw do
  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :leads
  resources :migrations
  resources :employees
  resources :quotes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  # get 'leads/new'
  
  root 'welcome#index'

  post 'lead' => 'leads#create'

  # post 'lead' => 'leads#sendgrid'
  

  get 'residential' => 'welcome#residential'

  get 'commercial' => 'welcome#commercial'

  # get '/admin' => 'rails_admin#admin'
  
  get 'quote' => 'welcome#quote'
  post 'quote' => 'quotes#create'

  get 'quote' => 'quotes#new'

  get 'map' => 'googlemaps#map'

  get '/intervention' => 'interventions#new'

  get 'get_buildings_by_customer/:customer_id', to: 'buildings#get_buildings_by_customer'  
  get '/building_search' => 'buildings#building_search'

  get 'get_batteries_by_buildings/:building_id', to: 'batteries#get_batteries_by_buildings'  
  get '/battery_search' => 'batteries#battery_search'

  get 'get_columns_by_batteries/:battery_id', to: 'columns#get_columns_by_batteries'  
  get '/column_search' => 'columns#column_search'

  get 'get_elevators_by_columns/:column_id', to: 'elevators#get_elevators_by_columns'  
  get '/elevator_search' => 'elevators#elevator_search'

end

app/models/lead.rb
class Lead < ApplicationRecord
    has_one_attached :attachement
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
      include SendGrid
      require 'sendgrid-ruby'
  require 'rest-client'
  require 'json'
  before_action :set_lead, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /leads or /leads.json
  def index
    @leads = Lead.all
  end

  def test
    puts "-------------"
    puts params[:contact]
  end

  # GET /leads/1 or /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    pp "new"
    @lead = Lead.new

  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads or /leads.json
  def create
    @lead = Lead.new(lead_params)
    

# using SendGrid's Ruby Library
# https://github.com/sendgrid/sendgrid-ruby

  
   

    respond_to do |format|
      if @lead.save
        sendgrid
        format.html { redirect_to "/", notice: "Your Information was successfully sent." }

        RestClient.post('https://rocketelevator-help.freshdesk.com/api/v2/tickets',
        {
        "type": "Feature Request",
        "status": 2,
        "priority": 1,
        "description": @lead.Full_Name_Of_The_Contact + " from " + @lead.Company_Name +
        " The contact " + @lead.Full_Name_Of_The_Contact + " from company " + @lead.Company_Name + 
        " can be reached at email " + @lead.Email + " and at phone number "+
        @lead.Phone + "." +
        @lead.Departement_In_Charge_Of_The_Elevators + " has a project named " + @lead.Project_Name + 
        " which would require contribution from Rocket Elevators. " + 
        + @lead.Project_Description +
        +" Attached Message: " + @lead.Message,
        #"attachments": [File.new(@lead.Attached_File_Stored_As_A_Binary_File,'rb')],
       "subject": "new ticket sample #{Time.now}",
        "email": "rocketelevator2@gmail.com"}.to_json, 
        {
          "Authorization": "Basic dlhubExKdWF6WkhOVGRKRjJmVnA6eA==",
          "Content-Type": "application/json"})

        # format.html { redirect_to "/" }
        # format.js { flash[:notice] = "Created order" } 
        # format.html { flash[:info] = "Success!!" }
        # redirect_to "/", alert: "Quote was successfully updated."
        # flash.now
        # format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1 or /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to lead_url(@lead), notice: "Lead was successfully updated." }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  def sendgrid 
    @lead = Lead.new(lead_params)
    from = SendGrid::Email.new(email: 'rocketelevators1165@gmail.com')
    to = SendGrid::Email.new(email: @lead.Email)
    subject = 'Thank you, your information has been sent successfully'
    content = SendGrid::Content.new(type: 'text/html', value: "  
      
<p>Greetings #{@lead.Full_Name_Of_The_Contact},</p>
</br>
</br>
<p>We thank you for contacting Rocket Elevators to discuss the opportunity to contribute to your project ' #{@lead.Project_Name} ' .</p>
</br>
<p>A representative from our team will be in touch with you very soon. We look forward to demonstrating the value of our solutions and help you choose the appropriate product given your requirements.</p>
</br>
<p>We'll Talk soon</p>
</br>
<p>The Rocket Team</p>
</br>
</br>
<img src='http://philippethivierge.xyz/assets/images/Logo.png' width='349px' height='123px' alt='Rocket Elevators Logo'>
")
    mail = SendGrid::Mail.new(from, subject, to, content)
    sg = SendGrid::API.new(api_key: ENV['SENDGRID_API_KEY'])
    response = sg.client.mail._('send').post(request_body: mail.to_json)
    pp "=================================================="
    puts response.status_code
    puts response.body
    pp "=================================================="
  end
  # DELETE /leads/1 or /leads/1.json
  def destroy
    @lead.destroy

    respond_to do |format|
      format.html { redirect_to leads_url, notice: "Lead was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lead_params
      params.permit(:Full_Name_Of_The_Contact, :Company_Name, :Email, :Phone, :Project_Name, :Project_Description, :Departement_In_Charge_Of_The_Elevators, :Message, :attachement)
    end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form', lead: @lead %>

<%# <%= link_to 'Show', @lead %> 
<%# <%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leads</h1>

<table>
  <thead>
    <tr>
      <th>Full name of the contact</th>
      <th>Company name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Project name</th>
      <th>Project description</th>
      <th>Departement in charge of the elevators</th>
      <th>Message</th>
      <th>Attached file stored as a binary file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.Full_Name_Of_The_Contact %></td>
        <td><%= lead.Company_Name %></td>
        <td><%= lead.Email %></td>
        <td><%= lead.Phone %></td>
        <td><%= lead.Project_Name %></td>
        <td><%= lead.Project_Description %></td>
        <td><%= lead.Departement_In_Charge_Of_The_Elevators %></td>
        <td><%= lead.Message %></td>
        <td><%= lead.Attached_File_Stored_As_A_Binary_File %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# <%= link_to 'New Lead', new_lead_path %> 

app/views/leads/new.html.erb
<%= render 'form', lead: @lead %>

<%# <%= link_to 'Back', leads_path %> 
<%# <%= link_to 'Show', @lead %>  

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name of the contact:</strong>
  <%= @lead.Full_Name_Of_The_Contact %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @lead.Company_Name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.Email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lead.Phone %>
</p>

<p>
  <strong>Project name:</strong>
  <%= @lead.Project_Name %>
</p>

<p>
  <strong>Project description:</strong>
  <%= @lead.Project_Description %>
</p>

<p>
  <strong>Departement in charge of the elevators:</strong>
  <%= @lead.Departement_In_Charge_Of_The_Elevators %>
</p>

<p>
  <strong>Message:</strong>
  <%= @lead.Message %>
</p>

<p>
  <strong>Attached file stored as a binary file:</strong>
  <%= @lead.Attached_File_Stored_As_A_Binary_File %>
</p>

<%# <%= link_to 'Edit', edit_lead_path(@lead) %> 
<%# <%= link_to 'Back', leads_path %> 