config/routes.rb
Rails.application.routes.draw do
  resources :interventions
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :leads
  resources :migrations
  resources :employees
  resources :quotes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  # get 'leads/new'
  
  root 'welcome#index'

  post 'lead' => 'leads#create'

  # post 'lead' => 'leads#sendgrid'
  

  get 'residential' => 'welcome#residential'

  get 'commercial' => 'welcome#commercial'

  # get '/admin' => 'rails_admin#admin'
  
  get 'quote' => 'welcome#quote'
  post 'quote' => 'quotes#create'

  get 'quote' => 'quotes#new'

  get 'map' => 'googlemaps#map'

  get '/intervention' => 'interventions#new'

  get 'get_buildings_by_customer/:customer_id', to: 'buildings#get_buildings_by_customer'  
  get '/building_search' => 'buildings#building_search'

  get 'get_batteries_by_buildings/:building_id', to: 'batteries#get_batteries_by_buildings'  
  get '/battery_search' => 'batteries#battery_search'

  get 'get_columns_by_batteries/:battery_id', to: 'columns#get_columns_by_batteries'  
  get '/column_search' => 'columns#column_search'

  get 'get_elevators_by_columns/:column_id', to: 'elevators#get_elevators_by_columns'  
  get '/elevator_search' => 'elevators#elevator_search'

end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /interventions or /interventions.json
  def index
    @interventions = Intervention.all

  end

  # GET /interventions/1 or /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new
    if !current_user.admin
      redirect_to :root, alert: "You are not authorized you have to be an admin to go on this page"
      return
    end
    @user = current_user
    @intervention = Intervention.new
    @customer = Customer.all
    @building = Building.all
    @battery = Battery.all
    @column = Column.all
    @elevator = Elevator.all
    @employee = Employee.all
  end

  # GET /interventions/1/edit
  def edit
  end

  # POST /interventions or /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)
    respond_to do |format|
      if @intervention.save
        format.html { redirect_to "/", notice: "Your Intervention was successfully sent." }

        comapny_name = Customer.find(@intervention.customer_id).Company_Name
        employeeFirstName = Employee.find(@intervention.employee_id).First_Name
        employeeLastName = Employee.find(@intervention.employee_id).Last_Name

        RestClient.post('https://rocketelevator-help.freshdesk.com/api/v2/tickets',
        {
         "type": "Incident",
         "status": 2,
         "priority": 1,
         "description": "Author : "+ current_user.email + " | " + " Company name : " + comapny_name + " | " +
         " BuildingID : " + @intervention.building_id.to_s + " | " + " BatteryID : " + @intervention.battery_id.to_s + " | " +" ColumnID : " + @intervention.column_id.to_s +
         " | " + " ElevatorID : " + @intervention.elevator_id.to_s +
         " | " + " Employee assigned : " + employeeFirstName + " " + employeeLastName + " | " + " Description : " + @intervention.report,
         "subject": "new ticket sample #{Time.now}",
         "email": "rocketelevator2@gmail.com"}.to_json, 
        {
          "Authorization": "Basic dlhubExKdWF6WkhOVGRKRjJmVnA6eA==",
          "Content-Type": "application/json"})

        format.html { redirect_to intervention_url(@intervention), notice: "Intervention was successfully created." }
        format.json { render :show, status: :created, location: @intervention }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to intervention_url(@intervention), notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy

    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.require(:intervention).permit(:author, :customer_id, :building_id, :battery_id, :column_id, :elevator_id, :employee_id, :start_date_and_time_of_the_intervention, :end_date_and_time_of_the_intervention, :result, :report, :status)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<div id="header" class="navbar-toggleable-md sticky header-md clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					<div class="container">

						<!-- Mobile Menu Button -->
						<button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
							<i class="fa fa-bars"></i>
						</button>

						<!-- Logo -->

						<a class="logo float-left scrollTo" href="/">
							<img src="assets/images/Logo.png" alt="" />
						</a>

						<!--
							Top Nav

							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
						<div class="navbar-collapse collapse float-right nav-main-collapse submenu-dark">
							<nav class="nav-main">

								<!--
									.nav-onepage
									Required for onepage navigation links

									Add .external for an external link!
								-->
								<ul id="topMain" class="nav nav-pills nav-main nav-onepage">
									<li class="active">
										<!-- HOME -->
										<a id="home-nav" href="/">
											HOME
										</a>
									</li>
									<li> 
										<!-- SERVICES -->
										<a id="services-nav" href="/#services">
											SERVICES
										</a>
									</li>
									<li>
										<!-- PORTFOLIO -->
										<a id="portfolio-nav" href="/#portfolio">
											PORTFOLIO
										</a>
									</li>
									<li>
										<!-- NEWS -->
										<a id="news-nav" href="/#news">
											NEWS
										</a>
									</li>

									<li>
										<!-- CLIENTS -->
										<a id="clients-nav" href="/#clients">
											CLIENTS
										</a>
									</li>
									<li>
									<!-- INTERVENTION -->
									<% if current_user == nil || !current_user.is_admin? %>
									<% elsif current_user.is_admin? %> 
									<%= link_to "INTERVENTION", "/interventions/new" %>
									<% end %>
									</li>
									<li>
										<!-- CONTACT -->
										<a id="contact-nav" href="/#contact">
											CONTACT
										</a>
									<%# <li>
										<!-- SUBMISSION -->
										<a id="quote-nav" href="quotes/new.html">
											SUBMISSION
										</a>
									</li> %>
          
									<%# <li>
										<!-- LOGIN -->
										<a id="login-nav" href="/admin">
											LOGIN
										</a>
									</li>
									<li>
										<!-- LOGOUT -->
										<a id="logout-nav" data-method="delete" href="/users/sign_out">
											LOGOUT
										</a>
									</li> %>

								</ul>

							</nav>
						</div>

					</div>
				</header>
				<!-- /Top Nav -->

			</div>
      <h1 style="font-size:4vw; text-align:center; background-color:#303030; color:white">
				<i>
					Intervention</i>
			</h1> <br><br>

<%= form_with(model: intervention, local: true) do |form| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
     <%= form.hidden_field :author, value: current_user&.employee&.id%>
  </div>

<div class="field center align">
  <div class="field" id="customer">
    <%= form.label :customer_id %>
    <% options = options_from_collection_for_select(@customer, "id", ->(customer) { "#{customer.id} - #{customer.Company_Name}" }) %>
    <%= form.select :customer_id,  options %>
  </div>
  <div class="field" id="building">
    <%= form.label :building_id %>
    <% options = options_from_collection_for_select(@building, "id", "id") %>
    <%= form.select :building_id,  options %>
  </div>

  <div class="field" id="battery">
    <%= form.label :battery_id %>
    <% options = options_from_collection_for_select(@battery, "id", "id")%>
    <%= form.select :battery_id,  options %>
  </div>

  <div class="field" id="column">
    <%= form.label :column_id %>
    <% options = options_from_collection_for_select(@column, "id", "id")%>
    <%= form.select :column_id,  options %>
  </div>

  <div class="field" id="elevator">
    <%= form.label :elevator_id %>
    <% options = options_from_collection_for_select(@elevator, "id", "id")%>
    <%= form.select :elevator_id,  options %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <% options = options_from_collection_for_select(@employee, "id",  ->(employee) { "#{employee.First_Name}  #{employee.Last_Name}" })%>
    <%= form.select :employee_id,  options %>
  </div>

  <div class="field">
    <%= form.label :report %>
    <%= form.text_area :report, cols: 50,  maxlength: 30000 %>
  </div>
  </br>
  <div class="actions">
    <%= form.submit :Submit %>
  </div>
</div>
<% end %>

			</form>

			<!-- /Parallax -->

			<footer id="footer">
				<div class="container">
					<div class="row">
						<!-- col #1 -->
						<div class="col-md-8">
							<h3 class="letter-spacing-1">WHY US?</h3>

							<!-- Small Description -->
							<p>
								We have the conviction that we create the most innovative and reliable
								products
								on the
								market.<a href="#contact"> Contact us</a> today for any questions you
								might
								have.</p>
							<h2><a href="tel:(418) 555-1234">(418) 555-1234</a></h2>
						</div>
						<!-- /col #1 -->

						<!-- col #2 -->
						<div class="col-md-4 col-sm-4">
							<h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

							<!-- Newsletter Form -->
							<p>Subscribe to Our Newsletter to get Important News & Offers</p>

							<form class="validate" action="php/newsletter.php" method="post"
								data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
									<input type="email" id="email" name="email" class="form-control required"
										placeholder="Enter your Email">
									<span class="input-group-btn">
										<button class="btn btn-primary" type="submit">Subscribe</button>
									</span>
								</div>
							</form>
							<!-- /Newsletter Form -->


						</div>
						<!-- /col #2 -->

					</div>


				</div>

				<div class="copyright">
					<div class="container">
						<ul class="float-right m-0 list-inline mobile-block">
							<li><a href="#">Terms &amp; Conditions</a></li>
							<li>&bull;</li>
							<li><a href="#">Privacy</a></li>
						</ul>
						&copy; All Rights Reserved, Company LTD
					</div>
				</div>

			</footer>
			<!-- /FOOTER -->

		</div>

app/views/interventions/edit.html.erb
<h1>Editing Intervention</h1>

<%= render 'form', intervention: @intervention %>

<%= link_to 'Show', @intervention %> |
<%= link_to 'Back', interventions_path %>

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Customer</th>
      <th>Building</th>
      <th>Battery</th>
      <th>Column</th>
      <th>Elevator</th>
      <th>Employee</th>
      <th>Start date and time of the intervention</th>
      <th>End date and time of the intervention</th>
      <th>Result</th>
      <th>Report</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= intervention.author %></td>
        <td><%= intervention.customer_id %></td>
        <td><%= intervention.building_id %></td>
        <td><%= intervention.battery_id %></td>
        <td><%= intervention.column_id %></td>
        <td><%= intervention.elevator_id %></td>
        <td><%= intervention.employee_id %></td>
        <td><%= intervention.start_date_and_time_of_the_intervention %></td>
        <td><%= intervention.end_date_and_time_of_the_intervention %></td>
        <td><%= intervention.result %></td>
        <td><%= intervention.report %></td>
        <td><%= intervention.status %></td>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb
<%= render 'form', intervention: @intervention %>

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @intervention.author %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @intervention.customer_id %>
</p>

<p>
  <strong>Building:</strong>
  <%= @intervention.building_id %>
</p>

<p>
  <strong>Battery:</strong>
  <%= @intervention.battery_id %>
</p>

<p>
  <strong>Column:</strong>
  <%= @intervention.column_id %>
</p>

<p>
  <strong>Elevator:</strong>
  <%= @intervention.elevator_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @intervention.employee_id %>
</p>

<p>
  <strong>Start date and time of the intervention:</strong>
  <%= @intervention.start_date_and_time_of_the_intervention %>
</p>

<p>
  <strong>End date and time of the intervention:</strong>
  <%= @intervention.end_date_and_time_of_the_intervention %>
</p>

<p>
  <strong>Result:</strong>
  <%= @intervention.result %>
</p>

<p>
  <strong>Report:</strong>
  <%= @intervention.report %>
</p>

<p>
  <strong>Status:</strong>
  <%= @intervention.status %>
</p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>